#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MANIFEST="$ROOT_DIR/docs-mkdocs/tutorials/notebooks.manifest"
NOTEBOOK_DIR="$ROOT_DIR/docs-mkdocs/tutorials/notebooks"
INDEX_FILE="$NOTEBOOK_DIR/index.md"

if [[ ! -f "$MANIFEST" ]]; then
  echo "Manifest not found: $MANIFEST" >&2
  exit 1
fi

mkdir -p "$NOTEBOOK_DIR"
# Clean previous synced notebooks/content (index is regenerated below).
find "$NOTEBOOK_DIR" -mindepth 1 -maxdepth 1 -exec rm -rf {} +

declare -a copied_paths=()

while IFS= read -r raw_line || [[ -n "$raw_line" ]]; do
  line="${raw_line%%#*}"
  line="$(echo "$line" | xargs)"
  [[ -z "$line" ]] && continue

  src="$ROOT_DIR/$line"
  if [[ ! -f "$src" ]]; then
    echo "Notebook listed in manifest was not found: $line" >&2
    exit 1
  fi

  rel_dir="$(dirname "$line")"
  mkdir -p "$NOTEBOOK_DIR/$rel_dir"
  cp "$src" "$NOTEBOOK_DIR/$line"
  copied_paths+=("$line")

done < "$MANIFEST"

{
  echo "# Notebook Gallery"
  echo
  echo 'This page is auto-generated by `./scripts/sync_docs_notebooks.sh`.'
  echo
  echo "To add a notebook:"
  echo '1. Add a path to `docs-mkdocs/tutorials/notebooks.manifest`.'
  echo '2. Run `./scripts/sync_docs_notebooks.sh`.'
  echo
  echo "## Curated notebooks"
  for rel in "${copied_paths[@]}"; do
    printf -- "- [%s](%s)\n" "$rel" "$rel"
  done
} > "$INDEX_FILE"

echo "Synced ${#copied_paths[@]} notebook(s) to $NOTEBOOK_DIR"
