#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MANIFEST="$ROOT_DIR/docs-mkdocs/tutorials/notebooks.manifest"
NOTEBOOK_DIR="$ROOT_DIR/docs-mkdocs/tutorials/notebooks"
INDEX_FILE="$NOTEBOOK_DIR/index.md"
HEADER_FILE="$NOTEBOOK_DIR/index.header.md"

if [[ ! -f "$MANIFEST" ]]; then
  echo "Manifest not found: $MANIFEST" >&2
  exit 1
fi

mkdir -p "$NOTEBOOK_DIR"

if [[ ! -f "$HEADER_FILE" ]]; then
  cat > "$HEADER_FILE" <<'EOF'
## For developers

The notebook listings above are auto-generated by `./scripts/sync_docs_notebooks.sh`.

To add a notebook:

1. Add a path to `docs-mkdocs/tutorials/notebooks.manifest`.
2. Run `./scripts/sync_docs_notebooks.sh`.
EOF
fi

# Clean previous synced notebooks/content (index is regenerated below).
# Preserve the editable developer notes file.
find "$NOTEBOOK_DIR" -mindepth 1 -maxdepth 1 ! -name "$(basename "$HEADER_FILE")" -exec rm -rf {} +

declare -a copied_paths=()

while IFS= read -r raw_line || [[ -n "$raw_line" ]]; do
  line="${raw_line%%#*}"
  line="$(echo "$line" | xargs)"
  [[ -z "$line" ]] && continue

  src="$ROOT_DIR/$line"
  if [[ ! -f "$src" ]]; then
    echo "Notebook listed in manifest was not found: $line" >&2
    exit 1
  fi

  rel_dir="$(dirname "$line")"
  mkdir -p "$NOTEBOOK_DIR/$rel_dir"
  cp "$src" "$NOTEBOOK_DIR/$line"
  copied_paths+=("$line")

done < "$MANIFEST"

copied_paths_json="$(printf '%s\n' "${copied_paths[@]}" | python3 -c 'import json, sys; print(json.dumps([line.strip() for line in sys.stdin if line.strip()]))')"

GENERATED_SECTION="$(mktemp)"

COPIED_PATHS_JSON="$copied_paths_json" python3 - > "$GENERATED_SECTION" <<'PY'
import json
import os

copied_paths = json.loads(os.environ["COPIED_PATHS_JSON"])
available = set(copied_paths)

sections = [
    (
        "Getting started",
        [
            ("Generative Model Construction (Model/Distribution APIs)", "examples/api/model_construction_tutorial.ipynb"),
            ("T-Maze Demo", "examples/envs/tmaze_demo.ipynb"),
            ("T-Maze Task with Distractors", "examples/envs/generalized_tmaze_demo.ipynb"),
            ("Cue Chaining Demo", "examples/envs/cue_chaining_demo.ipynb"),
            ("Graph worlds", "examples/envs/graph_worlds_demo.ipynb"),
            ("Demo: Knapsack Problem", "examples/envs/knapsack_demo.ipynb"),
        ],
    ),
    (
        "Sophisticated Inference",
        [
            (
                "Validating Sophisticated Inference (SI) Planning Algorithm using the T-Maze Task",
                "examples/experimental/sophisticated_inference/si_tmaze_SIvalidation.ipynb",
            ),
            (
                "Sophisticated inference on a T-Maze Task with Distractors",
                "examples/experimental/sophisticated_inference/si_generalized_tmaze.ipynb",
            ),
            (
                "Sophisticated inference on Graph Worlds",
                "examples/experimental/sophisticated_inference/si_graph_world.ipynb",
            ),
        ],
    ),
    (
        "Inductive Inference",
        [
            ("Inductive Inference Example", "examples/inductive_inference/inductive_inference_example.ipynb"),
            ("Inductive Inference Gridworld", "examples/inductive_inference/inductive_inference_gridworld.ipynb"),
        ],
    ),
    (
        "Parameter Learning",
        [("Learning Gridworld", "examples/learning/learning_gridworld.ipynb")],
    ),
    (
        "Fitting POMDPs to experimental / behavioral data",
        [("Fitting With `pybefit`", "examples/model_fitting/fitting_with_pybefit.ipynb")],
    ),
    (
        "Advanced",
        [
            (
                "Working with complex action dependencies",
                "examples/advanced/complex_action_dependency.ipynb",
            ),
            (
                "Using `pymdp` with a neural encoder",
                "examples/advanced/pymdp_with_neural_encoder.ipynb",
            ),
            (
                "Testing optimized inference methods",
                "examples/advanced/infer_states_optimization/methods_test.ipynb",
            ),
            ("Sparse Array Benchmarking", "examples/sparse/sparse_benchmark.ipynb"),
            (
                "Sophisticated inference with Monte Carlo Tree Search on TMaze with Distractors",
                "examples/experimental/sophisticated_inference/mcts_generalized_tmaze.ipynb",
            ),
            (
                "Sophisticated inference with Monte Carlo Tree Search on Graph World",
                "examples/experimental/sophisticated_inference/mcts_graph_world.ipynb",
            ),
            (
                "Comparing sequential inference algorithms",
                "examples/inference_and_learning/inference_methods_comparison.ipynb",
            ),
        ],
    ),
]

all_mapped_paths = {path for _, items in sections for _, path in items}
unmapped = [path for path in copied_paths if path not in all_mapped_paths]

print("# Notebook Gallery")
print()
print("## Curated notebooks")
print()

for section, items in sections:
    print(f"### {section}")
    for title, path in items:
        if path in available:
            print(f"- [{title}]({path})")
    print()

if unmapped:
    print("### Other notebooks")
    for path in unmapped:
        print(f"- [{path}]({path})")
PY

{
  cat "$GENERATED_SECTION"
  if [[ -s "$HEADER_FILE" ]]; then
    echo
    cat "$HEADER_FILE"
  fi
} > "$INDEX_FILE"

rm -f "$GENERATED_SECTION"

echo "Synced ${#copied_paths[@]} notebook(s) to $NOTEBOOK_DIR"
