#!/usr/bin/env python
# -*- coding: utf-8 -*-
# pylint: disable=no-member

""" Functions for performing variational inference on hidden states 

__author__: Conor Heins, Beren Millidge, Alexander Tschantz, Brennan Klein
"""

import numpy as np
from inferactively.core.maths import spm_dot, softmax, calc_free_energy


def run_fpi(A, obs, prior, n_observations, n_states, num_iter=10, dF=1.0, dF_tol=0.001):
    """
    Update marginal posterior beliefs about hidden states using variational fixed point iteration (FPI)
   
    Parameters
    ----------
    - 'A' [numpy nd.array (matrix or tensor or array-of-arrays)]:
        Observation likelihood of the generative model, mapping from hidden states to observations. 
        Used to invert generative model to obtain marginal likelihood over hidden states, given the observation
    - 'obs' [numpy 1D array or array of arrays (with 1D numpy array entries)]:
        The observation (generated by the environment). If single modality, this can be a 1D array (one-hot vector representation).
        If multi-modality, this can be an array of arrays (whose entries are 1D one-hot vectors).
    - 'prior' [numpy 1D array, array of arrays (with 1D numpy array entries)]:
        Prior beliefs of the agent, to be integrated with the marginal likelihood to obtain posterior
    -'num_iter' [int]:
        Number of variational fixed-point iterations to run.
    -'dF' [float]:
        Starting free energy gradient (dF/dt) before updating in the course of gradient descent.
    - 'dF_tol' [float]:
        Threshold value of the gradient of the variational free energy (dF/dt), to be checked at each iteration. If 
        dF <= dF_tol, the iterations are halted pre-emptively and the final marginal posterior belief(s) is(are) returned
  
    Returns
    ----------
    'qx' [numpy 1D array or array of arrays (with 1D numpy array entries):
        Marginal posterior beliefs over hidden states (single- or multi-factor) achieved via variational fixed point iteration (mean-field)
    """

    # get model dimensions
    n_modalities = len(n_observations)
    n_factors = len(n_states)

    """
    =========== Step 1 ===========
        Loop over the observation modalities and use the mean-field assumption to multiply 'induced posterior' onto
        a single joint likelihood over hidden factors [size n_states]
    """

    likelihood = np.ones(tuple(n_states))
    if n_modalities is 1:
        likelihood *= spm_dot(A, obs, obs_mode=True)
    else:
        for modality in range(n_modalities):
            likelihood *= spm_dot(A[modality], obs[modality], obs_mode=True)
    likelihood = np.log(likelihood + 1e-16)

    """
    =========== Step 2 ===========
        Create a flat posterior
    """

    qx = np.empty(n_factors, dtype=object)
    for factor in range(n_factors):
        qx[factor] = np.ones(n_states[factor]) / n_states[factor]

    """
    =========== Step 3 ===========
        Initialize initial free energy
    """
    prev_vfe = calc_free_energy(qx, prior, n_factors)

    """
    =========== Step 4 ===========
        If we have a single factor, we can just add prior and likelihood,
        other we run FPI
    """

    if n_factors == 1:
        qL = spm_dot(likelihood, qx, [0])
        return softmax(qL + prior[0])

    else:
        """
        =========== Step 5 ===========
        Run the FPI scheme
        """

        curr_iter = 0
        while curr_iter < num_iter:

            # Initialise variational free energy
            vfe = 0

            # describes the order in which we process factors
            factor_orders = [range(n_factors), range((n_factors - 1), -1, -1)]

            # process factors
            for factor_order in factor_orders:
                for factor in factor_order:
                    qL = spm_dot(likelihood, qx, [factor])
                    qx[factor] = softmax(qL + prior[factor])

            # calculate new free energy
            vfe = calc_free_energy(qx, prior, n_factors, likelihood)

            # stopping condition
            dF = np.abs(prev_vfe - vfe)
            prev_vfe = vfe

            curr_iter += 1

        return qx
